package main

type AutoGenerated struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Data struct {
		Color    string `json:"color"`
		Capacity string `json:"capacity"`
	} `json:"data,omitempty"`
}
